-- ============================================================
-- Venue Booking System — MySQL Schema
-- ============================================================

CREATE DATABASE IF NOT EXISTS venue_booking
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE venue_booking;

-- Users -------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    username        VARCHAR(80)  NOT NULL UNIQUE,
    email           VARCHAR(120) NOT NULL UNIQUE,
    password_hash   VARCHAR(256) NOT NULL,
    is_admin        TINYINT(1)   NOT NULL DEFAULT 0,
    created_at      DATETIME     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Venues ------------------------------------------------------
CREATE TABLE IF NOT EXISTS venues (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    location        VARCHAR(200) NOT NULL,
    capacity        INT          NOT NULL,
    price_per_hour  FLOAT        NOT NULL,
    amenities       TEXT,
    image_url       VARCHAR(300) DEFAULT '/static/images/default_venue.jpg',
    created_at      DATETIME     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Bookings ----------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    user_id         INT          NOT NULL,
    venue_id        INT          NOT NULL,
    event_date      DATE         NOT NULL,
    start_time      TIME         NOT NULL,
    end_time        TIME         NOT NULL,
    status          VARCHAR(20)  DEFAULT 'confirmed',
    created_at      DATETIME     DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE CASCADE,
    UNIQUE KEY uq_venue_slot (venue_id, event_date, start_time)
) ENGINE=InnoDB;

-- Notifications -----------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    user_id         INT          NOT NULL,
    message         TEXT         NOT NULL,
    is_read         TINYINT(1)   DEFAULT 0,
    created_at      DATETIME     DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Seed an admin user (password: admin123) ---------------------
-- Hash generated by: python -c "from werkzeug.security import generate_password_hash; print(generate_password_hash('admin123'))"
-- The hash below is valid for 'admin123' — regenerate if you change the password.
INSERT IGNORE INTO users (username, email, password_hash, is_admin)
VALUES ('admin', 'admin@venuebooking.com',
        'scrypt:32768:8:1$salt$placeholder_replace_with_real_hash', 1);

-- Seed sample venues ------------------------------------------
INSERT IGNORE INTO venues (name, location, capacity, price_per_hour, amenities, image_url) VALUES
('Grand Ballroom', 'Downtown', 500, 250.00, 'AC, Stage, Projector, Parking', '/static/images/venue1.jpg'),
('Lakeview Hall', 'Lakeside', 200, 120.00, 'AC, Garden, Parking', '/static/images/venue2.jpg'),
('Skyline Terrace', 'Hilltop', 150, 180.00, 'Open Air, Bar, DJ Setup', '/static/images/venue3.jpg'),
('Heritage Mansion', 'Old Town', 300, 200.00, 'AC, Heritage Décor, Valet', '/static/images/venue4.jpg'),
('Crystal Banquet', 'City Center', 400, 220.00, 'AC, LED Walls, Catering', '/static/images/venue5.jpg');
